export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const APP_LOADING = 'APP_LOADING';

export const LIST_WEBSITES = 'LIST_WEBSITES';
export const CHECKING_ATTACH_SCRIPT = 'CHECKING_ATTACH_SCRIPT';
export const UNAUTH_USER = 'UNAUTH_USER';
